# Generated by Django 5.2.5 on 2025-08-06 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supports_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        15, "L'utilisateur doit avoir au moins 15 ans selon le RGPD"
                    )
                ],
            ),
        ),
    ]
